variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind

default:
  image: artifactory.gz.cvte.cn/devops/cvte/nvm:14.18.3-v4

job_install:
  script:
    - echo "run"