# 默认执行顺序
stages:
  - .pre
  - build
  - test
  - deploy

  # build packs
build_win:
  stage: build
  script:
    - sleep 10
    - touch ./build/win.txt
    - echo "Build Windows Packs"
  artifacts:
    paths:
      - ./build/
    exclude:
      - .gitkeep
    expire_in: 1 days

build_linux:
  stage: build
  artifacts:
    paths:
      - ./build/
    exclude:
      - .gitkeep
    expire_in: 1 days
  script:
    - touch ./build/linux.txt
    - echo "Build Linux Packs"

build_mac:
  stage: build
  artifacts:
    paths:
      - ./build/
    exclude:
      - .gitkeep
    expire_in: 1 days
  script:
    - touch ./build/mac.txt
    - echo "Build Mac Packs"

# test packs
test_win:
  stage: test
  needs:
    - build_win
  dependencies:
    - build_win
  script:
    - sleep 10
    - echo "Test Windows Packs"

test_linux:
  stage: test
  dependencies:
    - build_linux
  needs:
    - build_linux
  script:
    - echo "Test Linux Packs"

test_mac:
  stage: test
  needs:
    - build_mac
  dependencies:
    - build_mac
  script:
    - echo "Test Mac Packs"

# deploy packs
deploy_win:
  stage: deploy
  needs:
    - test_win
  dependencies:
    - build_win
  script:
    - echo "Deploy Windows Packs"

deploy_linux:
  stage: deploy
  needs:
    - test_linux
  dependencies:
    - build_linux
  script:
    - echo "Deploy Linux Packs"

deploy_mac:
  stage: deploy
  needs:
    - test_mac
  dependencies: []    # 空列表代表不下载任何制品
  script:
    - echo "Deploy Mac Packs"