# 通过 gitops 项目做演示
#Job1:
#  trigger: MyGroup/MyProject

variables:
  IMAGE: "DEPLOY_IMAGE"

Job1:
  trigger:
    include:
      - local: "deploy/deploy.windows.yaml"
      - local: "deploy/deploy.linux.yaml"
    strategy: depend
    forward:
      yaml_variables: true  # 默认 true
      pipeline_variables: false # 默认 false
