# 默认执行顺序
stages:
  - build
  - test
  - deploy

  # build packs
build_win:
  stage: build
  script:
    - echo "Build Windows Packs"

build_linux:
  stage: build
  script:
    - echo "Build Linux Packs"

build_mac:
  stage: build
  script:
    - echo "Build Mac Packs"

# test packs
test_win:
  stage: test
  script:
    - echo "Test Windows Packs"

test_linux:
  stage: test
  script:
    - echo "Test Linux Packs"

test_mac:
  stage: test
  script:
    - echo "Test Mac Packs"

# deploy packs
deploy_win:
  stage: deploy
  script:
    - echo "Deploy Windows Packs"

deploy_linux:
  stage: deploy
  script:
    - echo "Deploy Linux Packs"

deploy_mac:
  stage: deploy
  script:
    - echo "Deploy Mac Packs"