# 简单循环作业，最大不允许超过 50
SimpleRepeatJob:
  script: echo "SimpleJob Run"
  parallel: 5


# 单任务执行多次，每次参数不同
DifferentParamsJob:
  script:
    - echo "Username ${NAME}, sleep ${SLEEP}"
    - sleep ${SLEEP}
  parallel:
    matrix:
      - NAME: "zhangsan"
        SLEEP:
          - 5
          - 4
      - NAME: ["lisi", "wanger"]
        SLEEP: [3, 1]
