# vars & jobs

variables:
  Status: "waiting"
  DEPLOY_ENV:
    value: "test"
    description: "发布环境变量"

stages:
  - S1
  - S2

Job1:
  stage: S1
  before_script:
    - export
    - Status="running"
    - echo "Job1 status ${Status}"
  script:
    - |
      echo "Job1 Run command 1"
      echo "Job1 Run command 2"
  after_script:
    - Status="Stop"
    - echo "Job1 status ${Status}"

Job2:
  stage: S2
  script:
    - >
      bash ./scripts/s2_job.sh
      Status="Ends"
      echo "Job2 status ${Status}"
