# default and inherit

default:
  retry: 2
  image: ruby:3.0
  interruptible: true


variables:
  VARIABLE1: "This is variable 1"
  VARIABLE2: "This is variable 2"
  VARIABLE3: "This is variable 3"


job1:
  script:
  - echo "This job does not inherit any default keywords."
  - echo "This job does not inherit any global variables."
  inherit:
    default: false
    variables: false

job2:
  script:
  - echo "This job inherits only the two listed default keywords. It does not inherit 'interruptible'."
  - echo "This job inherits only the two listed global variables. It does not inherit 'VARIABLE3'."
  inherit:
    default:
      - retry
      - image
    variables:
      - VARIABLE1
      - VARIABLE2
