Job1:
  script:
    - echo "Job1 Scripts Run"
  environment:
    name: test
    url: http://www.cvte.com/
    on_stop: clean_test_env

  resource_group: whatever_you_wat    # 不允许以左斜杠开始或结束


clean_test_env:
  script:
    - echo "Clean Test Env Job Runs"
  when: manual
  environment:
    name: test
    action: stop