# job & stage

stages:
  - S1
  - S2

Job1:
  stage: S1
  before_script:
    - echo "Job1 before script"
  script:
    - |
      echo "Job1 Run command 1"
      echo "Job1 Run command 2"
  after_script:
    - echo "Job1 after script"

Job2:
  stage: S2
  script:
    - >
      bash ./scripts/s2_job.sh
      echo "Job2 script ends"

Job3:
  stage: S2
  script:
    - echo "Job3 is running"

Job4:
  stage: .post
  script:
    - echo "Job4 is running"