Job1:
  script:
    - echo "Job1 Scripts Run"
    - sleep 60
  resource_group: whatever_you_wat    # 不允许以左斜杠开始或结束


Job2:
  trigger:
    include: .sub_pipeline.yaml
    strategy: depend
  resource_group: production