variables:
  IMAGE: "DEPLOY_IMAGE"

# 通过 gitops 项目做演示
#JobTriggerProject:
#  trigger:
#    project: "ci/Learning"
#    branch: "01.Runner_工作原理"

JobTriggerSubPipelines:
  trigger:
    include:
      - local: "deploy/windows.yaml"
      - local: "deploy/linux.yaml"
    strategy: depend
    forward:
      yaml_variables: true  # 默认 true
      pipeline_variables: false # 默认 false
