# vars & jobs


stages:
  - S1
  - S2
  - shared

.Shared: &shared
  stage: shared
  script:
    - echo "Shared scripts"

# extends
.BaseJob2:
  stage: S2
  script:
    - echo "Base Job2 scripts"

.BaseJob1:
  stage: S1
  script:
    - echo "Base Job1 scripts"

Job1:
  <<: *shared
  stage: S1

Job2:
  extends:
    - .BaseJob1
    - .BaseJob2
